//get product to show product detail
export const FETCH_PRODUCT_DETAILS_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_DETAILS_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_DETAILS_ERROR = "FETCH_PRODUCT_ERROR";