//get products to show productsList
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST ";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

//get product to show product detail
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const FETCH_CART_PRODUCTS_REQUETS = "FETCH_CART_PRODUCTS_REQUETS";
export const FETCH_CART_PRODUCTS_SUCCESS = "FETCH_CART_PRODUCTS_SUCCESS";
export const FETCH_CART_PRODUCTS_ERROR = "FETCH_CART_PRODUCTS_ERROR";

