export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST ";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';

//get products cart to show cart.productsList

export const GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST";
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS";
export const GET_CART_PRODUCTS_ERROR = "GET_CART_PRODUCTS_ERROR";   

//add product to cart

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR"; 