//get cart products
export const FETCH_CART_PRODUCTS_REQUETS = "FETCH_CART_PRODUCTS_REQUETS";
export const FETCH_CART_PRODUCTS_SUCCESS = "FETCH_CART_PRODUCTS_SUCCESS";
export const FETCH_CART_PRODUCTS_ERROR = "FETCH_CART_PRODUCTS_ERROR";

//add product to cart
export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

//remove product from cart
export const REMOVE_PRODUCT_FROM_CART_REQUEST = "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_ERROR = "REMOVE_PRODUCT_FROM_CART_ERROR";

//update cart total price 
export const UPDATE_CART_TOTAL_PRICE = "UPDATE_CART_TOTAL_PRICE";