//get products to show productsList
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST ";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";